"""Public launch-gate policy constants."""

from __future__ import annotations

from typing import Final

PUBLIC_TESTNET_MIN_DAYS: Final[int] = 30
PUBLIC_TESTNET_MIN_NODES: Final[int] = 100
GENESIS_BTC_CONFIRMATIONS: Final[int] = 6
GENESIS_BTC_SELECTION_RULE: Final[str] = "latest pre-ceremony block with 6 confirmations"
GENESIS_ETH_SELECTION_RULE: Final[str] = "latest finalized pre-ceremony block"

GENESIS_BTC_MIN_CONFIRMATIONS: Final[int] = GENESIS_BTC_CONFIRMATIONS
GENESIS_BITCOIN_SELECTION_RULE: Final[str] = GENESIS_BTC_SELECTION_RULE
GENESIS_ETHEREUM_SELECTION_RULE: Final[str] = GENESIS_ETH_SELECTION_RULE

__all__ = [
    "GENESIS_BITCOIN_SELECTION_RULE",
    "GENESIS_BTC_CONFIRMATIONS",
    "GENESIS_BTC_MIN_CONFIRMATIONS",
    "GENESIS_BTC_SELECTION_RULE",
    "GENESIS_ETHEREUM_SELECTION_RULE",
    "GENESIS_ETH_SELECTION_RULE",
    "PUBLIC_TESTNET_MIN_DAYS",
    "PUBLIC_TESTNET_MIN_NODES",
]
